# Generated by Django 5.0.6 on 2024-05-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(default='No email', max_length=254)),
                ('data_registration', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
