# Generated by Django 5.0.6 on 2024-06-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_story', models.CharField(default='', max_length=150)),
                ('list_players', models.TextField()),
                ('player_walks', models.IntegerField(default=0)),
                ('story', models.TextField()),
                ('number_of_round', models.IntegerField(default=1)),
                ('round', models.IntegerField(default=1)),
                ('data_game', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(default='No email', max_length=254)),
                ('data_registration', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
