# Generated by Django 5.0.6 on 2024-06-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='list_players',
            field=models.JSONField(default=list),
        ),
    ]
