# Generated by Django 5.0.6 on 2024-06-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='round',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='games',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
